language: node_js
node_js:
  - "4.2.6"

services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_script:
  - sleep 15

script:
  - chmod +x ./bin/setup.js
  - npm run-script test-travis
  - npm run gen-apidoc

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
