language: node_js
node_js:
  - "0.12"

services:
  - mongodb

before_script:
  - sleep 5

script:
  - npm run-script test-travis
  - npm run gen-apidoc

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"